### ISSUE TITLE
Nothing is saved

### ISSUE THREAD

**Issue by lostcause** [AM2studio/Laravel-SeoMeta#1]
Hi!

I tried to use your package, but because I am using Laravel 5.0.\* for my project, I forked it and changed the minimum Laravel requirements. I managed to install it, and configure it, the form fields show in the form, all seems to be just fine. But when I update my model, nothing gets inserted in seo_metas table. Is there something else besides what's in the documentation that I need to do? Could it be because I am using 5.0.*? Could you point me in the right direction?
Thank you!

**Comment by fico7489** [comment]
I updated readme. You must update $fillable in model:

protected $fillable = [
...
'seoMeta'
];

2016-02-25 9:18 GMT+01:00 lostcause notifications@github.com:
